-- 코드를 작성해주세요
SELECT 
    `e`.`ID` AS ID
FROM `ECOLI_DATA` AS `gp`
LEFT JOIN `ECOLI_DATA` AS `p` ON `gp`.`ID` = `p`.`PARENT_ID`
LEFT JOIN `ECOLI_DATA` e ON `p`.ID = e.`PARENT_ID`
WHERE gp.PARENT_ID IS NULL AND e.ID IS NOT NULL
ORDER BY e.ID