-- 코드를 입력하세요
# `REST_ID`, `REST_NAME`, `FOOD_TYPE`, `FAVORITES`, `ADDRESS`, `SCORE`
SELECT `INFO`.`REST_ID`, `INFO`.`REST_NAME`, `INFO`.`FOOD_TYPE`, `INFO`.`FAVORITES`, `INFO`.`ADDRESS`, ROUND(AVG(`REVIEW`.`REVIEW_SCORE`), 2) AS `SCORE`
FROM `REST_INFO` AS `INFO`
JOIN `REST_REVIEW` AS `REVIEW`
USING(`REST_ID`)
WHERE SUBSTRING(`INFO`.`ADDRESS`, 1, 2) = '서울'
GROUP BY `REVIEW`.`REST_ID`
ORDER BY `SCORE` DESC, `INFO`.`FAVORITES` DESC;